config/routes.rb
Rails.application.routes.draw do
  get 'astros/feed'
  get 'rates/feed'
  get 'rates/refresh'
  resources :astros
  resources :rates
  resources :reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_version.rb
class AppVersion < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astro.rb
class Astro < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :rates

  def latest_rate
    rates.last
  end

  def previous_rate
    (rates.last(2).reverse - [latest_rate]).first
  end

end

app/models/rate.rb
# require 'rake'
class Rate < ApplicationRecord
  belongs_to :currency

  def self.update
    %x[rails rates:updater]
  end
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/astros_controller.rb
class AstrosController < ApplicationController
  def feed
    @astros = Astro.all
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @astro = Astro.find(params[:id])
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def feed
    # @currencies = Currency.all
    @reports = Report.all
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @rate = Rate.find(params[:id])
  end

  def index
    @currencies = Currency.all
    latest_rate = Rate.last
    @timestamp = latest_rate.updated_at
  end

  def refresh
    Rate.update
    redirect_to rates_path
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def show
    @report = Report.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/astros/show.html.erb
<%= @astro.date %>
<%= @astro.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateChecker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rates/feed.html.erb
<h1>Rates#feed</h1>
<p>Find me in app/views/rates/feed.html.erb</p>

app/views/rates/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <th>幣別</th>
    <th>前次匯率</th>
    <th></th>
    <th>目前匯率 Updated at <%= @timestamp %></th>
  </thead>
  <% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.name %></td>
    <td><%= currency.previous_rate.try(:current_rate) %></td>
    <td> => </td>
    <td><%= currency.latest_rate.current_rate %></td>
  </tr>
  <% end %>
</table>
<hr>
<%= link_to("Refresh rates", rates_refresh_path, class: "btn btn-primary btn-lg pull-right") %>

app/views/rates/show.html.erb
<%= @rate.currency.name %> to NTD @ <%= @rate.current_rate %>

app/views/reports/show.html.erb
<%= @report.title %> @ <%= @report.updated_at.localtime.strftime("%Y-%m-%d %H:%M") %>
<hr>
<%= raw(@report.content) %>